### ISSUE TITLE
Reduce the type code amount

### ISSUE THREAD

**Issue by Avimitin** [bnoctis/simplistic-commits#2]
In my daily practices, almost all the commits can be classified by feature/fix/refactor. I think keeping the N, D, R, F codes is enough.

Like the test code T can be replaced with `N ci: add integration test for sth`.

**Comment by nc7s** [comment]
But why `N ci:` when you can just `CI:`?

**Comment by nc7s** [comment]
The example reminds me of something though: we can definitely use `+` and `-` to indicate new or removed things.
